# install-deps-aliyun.yml
---
- hosts: rancher-worker
  tasks:
    - name: install deps aliyun
      shell: bash /root/rancher2.4.5-offline/auto-install-aliyun-deps.sh
      register: shell_result

    - debug:
        var: shell_result.stdout_lines